# Generated by Django 3.2.23 on 2024-12-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='truckstop_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
