# Generated by Django 3.2.23 on 2024-12-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fuelstation_truckstop_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['location'], name='api_fuelsta_locatio_c6f98d_idx'),
        ),
    ]
